# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel_Heroes' do
  platform :ios, '12.0'
  use_frameworks!
  pod 'PagingCollectionViewLayout'
end
